fix: add missing types to utils.ts and errors.ts (#547)
* fix: add missing types to utils.ts

* fix: fix linter errors  about const-let,regex

* fix: ci/circleci: build -> MessagePort to Worker

* fix: update bufferToBase64UrlEncoded arg type

__tests__/utils.test.ts:120:39 - error TS2345: Argument of type 'Uint8Array' is not assignable to parameter of type 'Buffer'.

* fix: add Uint8Array to bufferToBase64UrlEncoded

passed the test in local branch

* fix: add missing type tofromPayload at errors.ts

Co-authored-by: Steve Hobbs <steve.hobbs@auth0.com>